version: "3.8"


volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/qgiraux/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/qgiraux/data/wordpress'

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    init: true
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
        - WP_USER
        - WP_PASSWORD
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
      container_name: wordpress
      image: wordpress:42
      init: true
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
        args:
          - MYSQL_DATABASE
          - MYSQL_USER
          - MYSQL_PASSWORD
      networks:
        - inception
      volumes:
        - wordpress:/var/www/html
      restart: always
      depends_on:
        - mariadb  

  nginx:
    container_name: nginx
    image: nginx:42
    init: true
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - mariadb
      - wordpress




